spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: skboy
    password: tgw215405
    url: jdbc:mysql://127.0.0.1:3306/diancan?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
  druid:
    test-on-borrow: true
    test-while-idle: true
server:
  servlet:
    context-path: /sell
wechat:
  # 公众账号, 授权
  mpAppId: wxf0a53ce437e0d879
  mpAppSecret: e37bf373e8215c07e643ce2deb544fa3

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9

  # 支付/商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617
    # 发起支付不需要证书, 退款需要
  keyPath: /var/
  notifyUrl: http://skboysell.natapp1.cc/sell/pay/notify
  #templateId:
    #  orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
projectUrl:
  wechatMpAuthorize: http://skboysell.natapp1.cc
  wechatOpenAuthorize: http://skboysell.natapp1.cc
  sell: http://skboysell.natapp1.cc
    #logging:
    #config:
  #pattern:
  #$console: "%d - %msg%n"
  #path: F:/log/tomcat/

