spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: skboy
    password: tgw215405
    url: jdbc:mysql://119.29.216.78:3306/diancan?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
  #config:
  #pattern:
    #$console: "%d - %msg%n"
  #path: F:/log/tomcat/
